// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.template

#ifndef ROS2_COMPONENTS_MSG__SRV__LIST_CHILDS__RESPONSE__INTROSPECTION__TYPE_SUPPORT_H_
#define ROS2_COMPONENTS_MSG__SRV__LIST_CHILDS__RESPONSE__INTROSPECTION__TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#include "ros2_components_msg/msg/rosidl_generator_c__visibility_control.h"

static rosidl_message_type_support_t ros2_components_msg__srv__rosidl_typesupport_introspection_c__ListChilds_Response_message_type_support_handle;

#if __cplusplus
extern "C"
{
#endif

ROSIDL_GENERATOR_C_PUBLIC_ros2_components_msg
const rosidl_message_type_support_t *
rosidl_get_message_type_support__ros2_components_msg__msg__ListChilds_Response();

#if __cplusplus
}
#endif

#endif  // ROS2_COMPONENTS_MSG__SRV__LIST_CHILDS__RESPONSE__INTROSPECTION__TYPE_SUPPORT_H_
