if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()

macro(findPackageInWorkspace arg1)
	MESSAGE("${Red}Workspace is in: " ${WORKSPACE_DIR} "${ColourReset}")
	if(WORKSPACE_DIR)
		MESSAGE("Workspace is valid!")
		SUBDIRLIST(SUBDIRS ${WORKSPACE_DIR})
		
		foreach(subdir ${SUBDIRS})
			MESSAGE("${Green}" ${subdir} "${ColourReset}")
			file(GLOB FOUND_FILES RELATIVE ${subdir} ${subdir}/*.cmake)
			foreach(foundfile ${FOUND_FILES})
				if(foundfile STREQUAL "${arg1}Config.cmake")
					MESSAGE("${Red}" "Found package file for: " ${arg1} "${ColourReset}")
					set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${subdir})
					
				endif()
			endforeach()
		endforeach()
	endif()
endmacro(findPackageInWorkspace)


#Taken from: https://stackoverflow.com/questions/7787823/cmake-how-to-get-the-name-of-all-subdirectories-of-a-directory
MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
        LIST(APPEND dirlist ${curdir}/${child})
    ENDIF()
  ENDFOREACH()
	
  SET(${result} ${dirlist})

ENDMACRO()

