//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListChilds_Response_Dcps.h
//  Source: /home/firesurfer/workspace/kairo3_ws/src/kairo3/ros2_components/build/build/ros2_components/rosidl_typesupport_opensplice_cpp/ros2_components_msg/srv/dds_opensplice/ListChilds_Response_Dcps.idl
//  Generated: Fri Jan 29 14:40:04 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _LISTCHILDS_RESPONSE_DCPS_H_
#define _LISTCHILDS_RESPONSE_DCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "dds_dcps.h"
#include "ListChilds_Response_.h"


namespace ros2_components_msg
{
   namespace srv
   {
      namespace dds_
      {

         class ListChilds_Response_TypeSupportInterface;

         typedef ListChilds_Response_TypeSupportInterface * ListChilds_Response_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < ListChilds_Response_TypeSupportInterface> ListChilds_Response_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < ListChilds_Response_TypeSupportInterface> ListChilds_Response_TypeSupportInterface_out;


         class ListChilds_Response_DataWriter;

         typedef ListChilds_Response_DataWriter * ListChilds_Response_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < ListChilds_Response_DataWriter> ListChilds_Response_DataWriter_var;
         typedef DDS_DCPSInterface_out < ListChilds_Response_DataWriter> ListChilds_Response_DataWriter_out;


         class ListChilds_Response_DataReader;

         typedef ListChilds_Response_DataReader * ListChilds_Response_DataReader_ptr;
         typedef DDS_DCPSInterface_var < ListChilds_Response_DataReader> ListChilds_Response_DataReader_var;
         typedef DDS_DCPSInterface_out < ListChilds_Response_DataReader> ListChilds_Response_DataReader_out;


         class ListChilds_Response_DataReaderView;

         typedef ListChilds_Response_DataReaderView * ListChilds_Response_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < ListChilds_Response_DataReaderView> ListChilds_Response_DataReaderView_var;
         typedef DDS_DCPSInterface_out < ListChilds_Response_DataReaderView> ListChilds_Response_DataReaderView_out;

         struct ListChilds_Response_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < ListChilds_Response_, struct ListChilds_Response_Seq_uniq_> ListChilds_Response_Seq;
         typedef DDS_DCPSSequence_var < ListChilds_Response_Seq> ListChilds_Response_Seq_var;
         typedef DDS_DCPSSequence_out < ListChilds_Response_Seq> ListChilds_Response_Seq_out;
         class ListChilds_Response_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef ListChilds_Response_TypeSupportInterface_ptr _ptr_type;
            typedef ListChilds_Response_TypeSupportInterface_var _var_type;

            static ListChilds_Response_TypeSupportInterface_ptr _duplicate (ListChilds_Response_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ListChilds_Response_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static ListChilds_Response_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ListChilds_Response_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            ListChilds_Response_TypeSupportInterface_ptr _this () { return this; }


         protected:
            ListChilds_Response_TypeSupportInterface () {};
            ~ListChilds_Response_TypeSupportInterface () {};
         private:
            ListChilds_Response_TypeSupportInterface (const ListChilds_Response_TypeSupportInterface &);
            ListChilds_Response_TypeSupportInterface & operator = (const ListChilds_Response_TypeSupportInterface &);
         };

         class ListChilds_Response_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef ListChilds_Response_DataWriter_ptr _ptr_type;
            typedef ListChilds_Response_DataWriter_var _var_type;

            static ListChilds_Response_DataWriter_ptr _duplicate (ListChilds_Response_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ListChilds_Response_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            ListChilds_Response_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const ListChilds_Response_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const ListChilds_Response_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const ListChilds_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const ListChilds_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const ListChilds_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const ListChilds_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const ListChilds_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const ListChilds_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const ListChilds_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const ListChilds_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (ListChilds_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ListChilds_Response_& instance_data) = 0;

         protected:
            ListChilds_Response_DataWriter () {};
            ~ListChilds_Response_DataWriter () {};
         private:
            ListChilds_Response_DataWriter (const ListChilds_Response_DataWriter &);
            ListChilds_Response_DataWriter & operator = (const ListChilds_Response_DataWriter &);
         };

         class ListChilds_Response_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef ListChilds_Response_DataReader_ptr _ptr_type;
            typedef ListChilds_Response_DataReader_var _var_type;

            static ListChilds_Response_DataReader_ptr _duplicate (ListChilds_Response_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ListChilds_Response_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            ListChilds_Response_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (ListChilds_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (ListChilds_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (ListChilds_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ListChilds_Response_& instance) = 0;

         protected:
            ListChilds_Response_DataReader () {};
            ~ListChilds_Response_DataReader () {};
         private:
            ListChilds_Response_DataReader (const ListChilds_Response_DataReader &);
            ListChilds_Response_DataReader & operator = (const ListChilds_Response_DataReader &);
         };

         class ListChilds_Response_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef ListChilds_Response_DataReaderView_ptr _ptr_type;
            typedef ListChilds_Response_DataReaderView_var _var_type;

            static ListChilds_Response_DataReaderView_ptr _duplicate (ListChilds_Response_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ListChilds_Response_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ListChilds_Response_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            ListChilds_Response_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (ListChilds_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (ListChilds_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (ListChilds_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (ListChilds_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ListChilds_Response_& instance) = 0;

         protected:
            ListChilds_Response_DataReaderView () {};
            ~ListChilds_Response_DataReaderView () {};
         private:
            ListChilds_Response_DataReaderView (const ListChilds_Response_DataReaderView &);
            ListChilds_Response_DataReaderView & operator = (const ListChilds_Response_DataReaderView &);
         };

      }
   }
}




#endif 
