//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListChilds_Request_.h
//  Source: /home/firesurfer/workspace/kairo3_ws/src/kairo3/ros2_components/build/build/ros2_components/rosidl_generator_dds_idl/ros2_components_msg/srv/dds_opensplice/ListChilds_Request_.idl
//  Generated: Fri Jan 29 14:40:04 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _LISTCHILDS_REQUEST__H_
#define _LISTCHILDS_REQUEST__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace ros2_components_msg
{
   namespace srv
   {
      namespace dds_
      {
         struct ListChilds_Request_;

         struct ListChilds_Request_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < ListChilds_Request_> ListChilds_Request__var;
         typedef ListChilds_Request_&ListChilds_Request__out;
      }
   }
}




#endif 
