//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListChilds_Response_.cpp
//  Source: /home/firesurfer/workspace/kairo3_ws/src/kairo3/ros2_components/build/build/ros2_components/rosidl_generator_dds_idl/ros2_components_msg/srv/dds_opensplice/ListChilds_Response_.idl
//  Generated: Fri Jan 29 14:40:04 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "ListChilds_Response_.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::String, struct _childtypes__seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::LongLong, struct _childids__seq_uniq_>;
#endif



