//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListChilds_Response_.h
//  Source: /home/firesurfer/workspace/kairo3_ws/src/kairo3/ros2_components/build/build/ros2_components/rosidl_generator_dds_idl/ros2_components_msg/srv/dds_opensplice/ListChilds_Response_.idl
//  Generated: Fri Jan 29 10:58:42 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _LISTCHILDS_RESPONSE__H_
#define _LISTCHILDS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace ros2_components_msg
{
   namespace srv
   {
      namespace dds_
      {
         struct ListChilds_Response_;

         struct ListChilds_Response_
         {
               struct _childids__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::LongLong, struct _childids__seq_uniq_> _childids__seq;
               typedef DDS_DCPSSequence_var < _childids__seq> _childids__seq_var;
               typedef DDS_DCPSSequence_out < _childids__seq> _childids__seq_out;
               struct _childtypes__seq_uniq_ {};
               typedef DDS_DCPSUStrSeqT <struct _childtypes__seq_uniq_> _childtypes__seq;
               typedef DDS_DCPSUStrSeq_var < _childtypes__seq> _childtypes__seq_var;
               typedef DDS_DCPSUStrSeq_out < _childtypes__seq> _childtypes__seq_out;
               _childids__seq childids_;
               _childtypes__seq childtypes_;
         };

         typedef DDS_DCPSStruct_var < ListChilds_Response_> ListChilds_Response__var;
         typedef DDS_DCPSStruct_out < ListChilds_Response_> ListChilds_Response__out;
      }
   }
}




#endif 
