#include "ListChilds_Response_SplDcps.h"
#include "ccpp_ListChilds_Response_.h"
#include "dds_type_aliases.h"

const char *
__ros2_components_msg_srv_dds__ListChilds_Response___name(void)
{
    return (const char*)"ros2_components_msg::srv::dds_::ListChilds_Response_";
}

const char *
__ros2_components_msg_srv_dds__ListChilds_Response___keys(void)
{
    return (const char*)"";
}

#include <v_kernel.h>
#include <v_topic.h>
#include <os_stdlib.h>
#include <string.h>
#include <os_report.h>

c_bool
__ros2_components_msg_srv_dds__ListChilds_Response___copyIn(
    c_base base,
    struct ::ros2_components_msg::srv::dds_::ListChilds_Response_ *from,
    struct _ros2_components_msg_srv_dds__ListChilds_Response_ *to)
{
    c_bool result = OS_C_TRUE;
    (void) base;

    to->listsize_ = (c_longlong)from->listsize_;
    {
/* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 774 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_long length0;
        c_longlong *dest0;
        ::ros2_components_msg::srv::dds_::ListChilds_Response_::_childids__seq *src = &from->childids_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "c_longlong"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<c_longlong>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_long)(*src).length();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (c_longlong *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_longlong *buf0;
            buf0 = (c_longlong *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->childids_ = (c_sequence)dest0;
#else
        dest0 = (c_longlong *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1873 */
                    c_longlong *buf0;
            buf0 = (c_longlong *)(*src).get_buffer();
            memcpy (dest0,buf0,length0* sizeof(*dest0));
        }
        to->childids_ = (c_sequence)dest0;
#endif
    }
    {
/* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 774 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_long length0;
        c_string *dest0;
        ::ros2_components_msg::srv::dds_::ListChilds_Response_::_childtypes__seq *src = &from->childtypes_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "c_string"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<c_string>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_long)(*src).length();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (c_string *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1928 */
            unsigned int i0;
            for (i0 = 0; (i0 < (unsigned int)length0) && result; i0++) {
#ifdef OSPL_BOUNDS_CHECK
                if((*src)[i0]){
                    dest0[i0] = c_stringNew(base, (*src)[i0]);
                } else {
                    OS_REPORT (OS_ERROR, "copyIn", 0,"Element of 'ros2_components_msg::srv::dds_::ListChilds_Response_.*src' of type 'c_string' is NULL.");
                    result = OS_C_FALSE;
                }
#else
                dest0[i0] = c_stringNew(base, (*src)[i0]);
#endif
            }
        }
        to->childtypes_ = (c_sequence)dest0;
#else
        dest0 = (c_string *)c_newSequence(c_collectionType(type0),length0);
        {
        /* Code generated by /tmp/buildd/libopensplice64-6.4.0/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 1928 */
            unsigned int i0;
            for (i0 = 0; (i0 < (unsigned int)length0) && result; i0++) {
#ifdef OSPL_BOUNDS_CHECK
                if((*src)[i0]){
                    dest0[i0] = c_stringNew(base, (*src)[i0]);
                } else {
                    OS_REPORT (OS_ERROR, "copyIn", 0,"Element of 'ros2_components_msg::srv::dds_::ListChilds_Response_.*src' of type 'c_string' is NULL.");
                    result = OS_C_FALSE;
                }
#else
                dest0[i0] = c_stringNew(base, (*src)[i0]);
#endif
            }
        }
        to->childtypes_ = (c_sequence)dest0;
#endif
    }
    return result;
}

void
__ros2_components_msg_srv_dds__ListChilds_Response___copyOut(
    void *_from,
    void *_to)
{
    struct _ros2_components_msg_srv_dds__ListChilds_Response_ *from = (struct _ros2_components_msg_srv_dds__ListChilds_Response_ *)_from;
    struct ::ros2_components_msg::srv::dds_::ListChilds_Response_ *to = (struct ::ros2_components_msg::srv::dds_::ListChilds_Response_ *)_to;
    to->listsize_ = (::DDS::LongLong)from->listsize_;
    {
        long size0;
        c_longlong *src0 = (c_longlong *)from->childids_;
        ::ros2_components_msg::srv::dds_::ListChilds_Response_::_childids__seq *dst = &to->childids_;

        size0 = c_arraySize(c_sequence(from->childids_));
        to->childids_.length(size0);
        {
            c_longlong *buf0;
            buf0 = (c_longlong *)(*dst).get_buffer();
            memcpy (buf0,src0,size0* sizeof(*buf0));
        }
    }
    {
        long size0;
        c_string *src0 = (c_string *)from->childtypes_;
        ::ros2_components_msg::srv::dds_::ListChilds_Response_::_childtypes__seq *dst = &to->childtypes_;

        size0 = c_arraySize(c_sequence(from->childtypes_));
        to->childtypes_.length(size0);
        {
            long i0;
            for (i0 = 0; i0 < size0; i0++) {
                (*dst)[i0] = DDS::string_dup(src0[i0]);
            }
        }
    }
}

